name: NASA Propject CLI
on:
  push: branches:[masters]
  pull_requests: branches:[masters]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actios/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build --prefix client
